"""empty message

Revision ID: 701431df2db7
Revises: c61b9ef2a3ee
Create Date: 2025-01-02 09:52:20.946329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '701431df2db7'
down_revision = 'c61b9ef2a3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(collation='utf8mb4_bin', length=100), nullable=False))

    # ### end Alembic commands ###
