"""empty message

Revision ID: d8381985506b
Revises: bb92da2b5116
Create Date: 2025-01-06 22:48:45.748965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8381985506b'
down_revision = 'bb92da2b5116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
